name: Deploy document

on:
  push:
    branches:
      - rewrite
    
jobs:
  deploy:
    name: Deploy document
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build documentation
        run: |
          pip3 install -U .
          pip3 install pdoc3
          pdoc --html -o html --force sanic_discord
      
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: html
          commit_message: Deploy documentation
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com