name: Deploy to pypi

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install setuptools twine wheel
      - name: Build for upload
        run: |
          python3 setup.py sdist bdist_wheel
      - name: Upload package
        run: |
          twine check dist/*
          twine -u "__token__" -p ${{ secrets.PYPI_ACCESS_TOKEN }} upload dist/*